# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
import sys
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView


class Ui_s_cals(object):
    def __init__(self):
        self.content=[]
        self.memory=[]
        self.result=0
        self.operators=['+','-','*','/']
    def setupUi(self, s_cals):
        s_cals.setObjectName("s_cals")
        s_cals.resize(300, 500)
        s_cals.setWindowTitle("Calc voe")

        self.pushButton_n9 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n9.setGeometry(QtCore.QRect(150, 190, 61, 61))
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.pushButton_n9.setText("9")

        self.pushButton_n8 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n8.setGeometry(QtCore.QRect(80, 190, 61, 61))
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.pushButton_n8.setText("8")

        self.pushButton_n7 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n7.setGeometry(QtCore.QRect(10, 190, 61, 61))
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.pushButton_n7.setText("7")

        self.pushButton_n6 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n6.setGeometry(QtCore.QRect(150, 260, 61, 61))
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.pushButton_n6.setText("6")

        self.pushButton_n5 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n5.setGeometry(QtCore.QRect(80, 260, 61, 61))
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.pushButton_n5.setText("5")

        self.pushButton_n4 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n4.setGeometry(QtCore.QRect(10, 260, 61, 61))
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.pushButton_n4.setText("4")

        self.pushButton_n3 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n3.setGeometry(QtCore.QRect(150, 330, 61, 61))
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.pushButton_n3.setText("3")

        self.pushButton_n2 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n2.setGeometry(QtCore.QRect(80, 330, 61, 61))
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.pushButton_n2.setText("2")

        self.pushButton_n1 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n1.setGeometry(QtCore.QRect(10, 330, 61, 61))
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.pushButton_n1.setText("1")

        self.pushButton_n0 = QtWidgets.QPushButton(s_cals)
        self.pushButton_n0.setGeometry(QtCore.QRect(80, 400, 61, 61))
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.pushButton_n0.setText("0")

        self.pushButton_smem = QtWidgets.QPushButton(s_cals)
        self.pushButton_smem.setGeometry(QtCore.QRect(10, 400, 61, 61))
        self.pushButton_smem.setAutoFillBackground(False)
        self.pushButton_smem.setObjectName("pushButton_smem")
        self.pushButton_smem.setText("M")

        self.pushButton_sdot = QtWidgets.QPushButton(s_cals)
        self.pushButton_sdot.setGeometry(QtCore.QRect(150, 400, 61, 61))
        self.pushButton_sdot.setAutoFillBackground(False)
        self.pushButton_sdot.setObjectName("pushButton_sdot")
        self.pushButton_sdot.setText(",")

        self.pushButton_s_equal = QtWidgets.QPushButton(s_cals)
        self.pushButton_s_equal.setGeometry(QtCore.QRect(220, 400, 61, 61))
        self.pushButton_s_equal.setAutoFillBackground(False)
        self.pushButton_s_equal.setObjectName("pushButton_s_equal")
        self.pushButton_s_equal.setText("=")

        self.pushButton_smultiply = QtWidgets.QPushButton(s_cals)
        self.pushButton_smultiply.setGeometry(QtCore.QRect(220, 190, 61, 61))
        self.pushButton_smultiply.setAutoFillBackground(False)
        self.pushButton_smultiply.setObjectName("pushButton_smultiply")
        self.pushButton_smultiply.setText("*")

        self.pushButton_sminus = QtWidgets.QPushButton(s_cals)
        self.pushButton_sminus.setGeometry(QtCore.QRect(220, 260, 61, 61))
        self.pushButton_sminus.setAutoFillBackground(False)
        self.pushButton_sminus.setObjectName("pushButton_sminus")
        self.pushButton_sminus.setText("-")

        self.pushButton_splus = QtWidgets.QPushButton(s_cals)
        self.pushButton_splus.setGeometry(QtCore.QRect(220, 330, 61, 61))
        self.pushButton_splus.setAutoFillBackground(False)
        self.pushButton_splus.setObjectName("pushButton_splus")
        self.pushButton_splus.setText("+")

        self.pushButton_left_bracket = QtWidgets.QPushButton(s_cals)
        self.pushButton_left_bracket.setGeometry(QtCore.QRect(10, 140, 61, 41))
        self.pushButton_left_bracket.setAutoFillBackground(False)
        self.pushButton_left_bracket.setObjectName("pushButton_left_bracket")
        self.pushButton_left_bracket.setText("(")

        self.pushButton_right_bracket = QtWidgets.QPushButton(s_cals)
        self.pushButton_right_bracket.setGeometry(QtCore.QRect(80, 140, 61, 41))
        self.pushButton_right_bracket.setAutoFillBackground(False)
        self.pushButton_right_bracket.setObjectName("pushButton_right_bracket")
        self.pushButton_right_bracket.setText(")")

        self.pushButton_back = QtWidgets.QPushButton(s_cals)
        self.pushButton_back.setGeometry(QtCore.QRect(150, 140, 61, 41))
        self.pushButton_back.setAutoFillBackground(False)
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_back.setText("←")

        self.pushButton_sdivide = QtWidgets.QPushButton(s_cals)
        self.pushButton_sdivide.setGeometry(QtCore.QRect(220, 140, 61, 41))
        self.pushButton_sdivide.setAutoFillBackground(False)
        self.pushButton_sdivide.setObjectName("pushButton_sdivide")
        self.pushButton_sdivide.setText("÷")

        self.pushButton_smemminus = QtWidgets.QPushButton(s_cals)
        self.pushButton_smemminus.setGeometry(QtCore.QRect(220, 90, 61, 41))
        self.pushButton_smemminus.setAutoFillBackground(False)
        self.pushButton_smemminus.setObjectName("pushButton_smemminus")
        self.pushButton_smemminus.setText("M-")

        self.pushButton_sqrt = QtWidgets.QPushButton(s_cals)
        self.pushButton_sqrt.setGeometry(QtCore.QRect(80, 90, 61, 41))
        self.pushButton_sqrt.setAutoFillBackground(False)
        self.pushButton_sqrt.setObjectName("pushButton_sqrt")
        self.pushButton_sqrt.setText("√")

        self.pushButton_ssqr = QtWidgets.QPushButton(s_cals)
        self.pushButton_ssqr.setGeometry(QtCore.QRect(10, 90, 61, 41))
        self.pushButton_ssqr.setAutoFillBackground(False)
        self.pushButton_ssqr.setObjectName("pushButton_ssqr")
        self.pushButton_ssqr.setText("^")

        self.pushButton_smemplus = QtWidgets.QPushButton(s_cals)
        self.pushButton_smemplus.setGeometry(QtCore.QRect(150, 90, 61, 41))
        self.pushButton_smemplus.setAutoFillBackground(False)
        self.pushButton_smemplus.setObjectName("pushButton_smemplus")
        self.pushButton_smemplus.setText("M+")

        self.pushButton_help = QtWidgets.QPushButton(s_cals)
        self.pushButton_help.setGeometry(QtCore.QRect(0, 0, 25, 30))
        self.pushButton_help.setObjectName("pushButton_help")
        self.pushButton_help.setText("?")

        self.output1 = QtWidgets.QLabel(s_cals)
        self.output1.setGeometry(QtCore.QRect(20, 10, 251, 40))
        self.output1.setFont(QFont('Comic Sans MS', 15))
        self.output1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.output1.setObjectName("output1")

        self.output2 = QtWidgets.QLabel(s_cals)
        self.output2.setGeometry(QtCore.QRect(20, 41, 251, 71))
        self.output2.setFont(QFont('Comic Sans MS', 20))
        self.output2.setObjectName("output2")

        self.retranslateUi(s_cals)

        QtCore.QMetaObject.connectSlotsByName(s_cals)
        self.pushButton_n0.clicked.connect(lambda:self.print("0"))
        self.pushButton_n1.clicked.connect(lambda: self.print("1"))
        self.pushButton_n2.clicked.connect(lambda: self.print("2"))
        self.pushButton_n3.clicked.connect(lambda: self.print("3"))
        self.pushButton_n4.clicked.connect(lambda: self.print("4"))
        self.pushButton_n5.clicked.connect(lambda: self.print("5"))
        self.pushButton_n6.clicked.connect(lambda: self.print("6"))
        self.pushButton_n7.clicked.connect(lambda: self.print("7"))
        self.pushButton_n8.clicked.connect(lambda: self.print("8"))
        self.pushButton_n9.clicked.connect(lambda: self.print("9"))
        self.pushButton_back.clicked.connect(self.delete)
        self.pushButton_splus.clicked.connect(lambda: self.print("+"))
        self.pushButton_sminus.clicked.connect(lambda: self.print("-"))
        self.pushButton_smultiply.clicked.connect(lambda: self.print("*"))
        self.pushButton_sdot.clicked.connect(lambda: self.print("."))
        self.pushButton_ssqr.clicked.connect(lambda: self.print("**"))
        self.pushButton_smem.clicked.connect(lambda: self.print("**"))
        self.pushButton_smemplus.clicked.connect(lambda: self.print("**"))
        self.pushButton_smemminus.clicked.connect(lambda: self.print("**"))

    def retranslateUi(self, s_cals):
        _translate = QtCore.QCoreApplication.translate

    def change(self, command):
        self.content.append(command)

    def print(self,number):
        self.content.append(number)
        print(self.content)
        self.output1.setText(''.join(self.content))
        temp=''.join(self.content)
        try:
            temp=eval(temp)
            self.output2.setText(str(temp))
        except:
            pass


    def delete(self):
        if len(self.content)!=0:
            self.content.pop()
            print(self.content)
            self.output1.setText(''.join(self.content))
            temp = ''.join(self.content)
            try:
                temp = eval(temp)
                self.output2.setText(str(temp))
            except:
                pass
            if len(self.content)==0:
                self.output2.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    s_cals = QtWidgets.QWidget()
    ui = Ui_s_cals()
    ui.setupUi(s_cals)
    s_cals.show()
    sys.exit(app.exec_())
